name: riassigner-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - autopep8
  - numpy
  - matchms >=0.14.0
  - pint >= 0.17
  - pip
  - pandas
  - prospector
  - pytest
  - pytest-cov
  - python >=3.7
  - rope
  - scipy
  - build
  - twine
  - pip:
    - -e ..[dev]