name: riassigner-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >=3.7
  - matchms >=0.14.0,<0.18.0
  - pint >=0.17,<0.20
  - pandas
  - scipy
  - prospector
  - pytest
  - pytest-cov
