name: riassigner
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matchms >=0.14.0,<0.18.0
  - pandas
  - pint >=0.17,<0.20
  - python >=3.8
  - scipy
  - poetry
