name: riassigner-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - autopep8
  - numpy
  - matchms >=0.14.0,<0.18.0
  - pint >=0.17,<0.20
  - pip
  - pandas
  - prospector
  - pytest
  - pytest-cov
  - python >=3.8
  - rope
  - scipy
  - build
  - twine
  - poetry
  - pip:
    - -e ..[dev]
