name: riassigner-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - autopep8
  - numpy
  - matchms >=0.9.1
  - pint >= 0.17
  - pip
  - pandas
  - prospector
  - pytest
  - pytest-cov
  - python >=3.7,<3.9
  - rope
  - scipy
  - pip:
    - -e ..[dev]