name: riassigner-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matchms >=0.9.0
  - pip
  - pandas
  - prospector
  - pytest
  - pytest-cov
  - python >=3.7,<3.9
  - rope
  - pip:
    - -e ..[dev]