{% set name = "RIAssigner" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

extra:
  channels:
    - conda-forge
    - bioconda

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  skip: True # [py2k]
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  build:
    - conda-build
    - conda-verify
    - pytest-runner
    - python
    - setuptools
  host:
    - python >=3.7,<3.9
    - pip
    - pytest-runner
    - setuptools
  run:
    - numpy
    - matchms >=0.82
    - pip
    - pandas
    - python >=3.7,<3.9

test:
  imports:
    - RIAssigner

about:
  home: https://github.com/hechth/RIAssigner
  license: MIT
  license_file: LICENSE
  summary: 'GC-MS retention index calculation'
  description: |
    RIAssigner is a python tool for retention index (RI) computation for GC-MS data
  dev_url: https://github.com/hechth/RIAssigner

extra:
  recipe-maintainers:
    - hechth