name: Anaconda Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  first_check:
    name: first code check / python-3.8 / ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python info
        run: |
          which python
          python --version
      - name: Build package and create dev environment
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Test with coverage
        run: |
          pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
          
  anaconda_dev:
    name: Anaconda build and test documentation / python-3.8 / ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: first_check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Create riassigner-dev environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: riassigner-dev
          auto-update-conda: true
          environment-file: conda/environment-dev.yml
          python-version: 3.8
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda env list
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Show environment variables
        shell: bash -l {0}
        run: |
          env | sort
      - name: Test with coverage
        shell: bash -l {0}
        run: |
          pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
      - name: Correct coverage paths
        run: sed -i "s+$PWD/++g" coverage.xml

  anaconda_build:
    name: Anaconda build / python-3.8 / ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: first_check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Create riassigner-build environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: riassigner-build
          auto-update-conda: true
          environment-file: conda/environment-build.yml
          python-version: 3.8
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda env list
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Show environment variables
        shell: bash -l {0}
        run: |
          env | sort
      - name: Build the conda package
        shell: bash -l {0}
        run: |
          export BUILDDIR=$RUNNER_TEMP/riassigner/_build
          [ "$RUNNING_OS" = "Windows" ] && export BUILDDIR=$RUNNER_TEMP\\riassigner\\_build\\
          conda config --set anaconda_upload no
          conda build --numpy 1.18.1 --no-include-recipe \
            --channel bioconda --channel conda-forge \
            --croot ${BUILDDIR} \
            ./conda
      - name: Upload package artifact from build
        uses: actions/upload-artifact@v2
        with:
          name: conda-package-artifact
          path: ${{ runner.temp }}/riassigner/_build
