# This is a basic workflow to help you get started with Actions

name: Mermaid

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Compile Mermaid Markdown
        # You may pin to the exact commit or the version.
        # uses: neenjaw/compile-mermaid-markdown-action@623a9c32deb506d5418ed46510c26b3995e3edbf
        uses: neenjaw/compile-mermaid-markdown-action@0.2.4
        with:
        # the path to the files to compile
          files: docs/diagram.md
          # Where to output the file - std otherwise
          output: docs
